### PR TITLE
More examples

### PR DESCRIPTION
**Pull request by pnorbert**

### CODE REVIEW

**Comment by pnorbert** [comment]
@chuckatkins @williamfgc Can one of you please change the azure build to depend on ornladios/adios2 docker account and that it builds 2.7.0 now. Checks are failing because I require adios 2.7.0 but williamfgc/ does not have a docker image for it. Thanks

**Comment by williamfgc** [comment]
Hi @pnorbert this is pretty awesome work. I'd migrate to GitHub Actions as it's more simple to maintain for the long run, I can work with you @chuckatkins or @dmitry-ganyushin . I kind of forgot about azure pipelines and I haven't had time to maintain those images in williamfgc/, I just picked azure-pipelines as this repo predates GitHub Actions. If @chuckatkins has an image ready for 2.7.0 I'd just reuse it. Let me know.

**Comment by chuckatkins** [comment]
I'm going to drop the azure pipelines from the CI in this PR, get it merged, and then follow up with adding github actions

**Review by williamfgc — APPROVED** [review]
Look good to me. I'd give the GitHub Actions CI @chuckatkins is working on a shot before merging.

**Comment by chuckatkins** [comment]
This should be good now.  After this merges I'll follow up with adding GHA CI that uses the release docker images built by adios2.

**Pull request merged**
